yaab_corp/applications/dashboard/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'dashboard_app'

urlpatterns = [
    path("",views.DashboardView.as_view(), name="index"),
    path('preguntas-respuestas/',views.PreguntasRespuestas.as_view(),name='preguntas_respuestas'),
    path('productos/productos-gral/',views.ProductosView.as_view(),name='productos_gral'),
    ##### producto #####
    path("dashboard/productos/nuevo-producto/",views.CreateProductosView.as_view(),name="nuevo_productos"),
    path('dashboard/productos/editar-productos/<int:pk>/',views.EditarProducto.as_view(),name='editar_productos'),
    path('dashboard/productos/eliminar-productos/<int:pk>/',views.EliminarProducto.as_view(),name='eliminar_productos'),
    
    ##### producto #####
    ##### plazo #####
    path("dashboard/plazos/nuevo-plazo/", views.CreatePlazoView.as_view(), name="nuevo_plazo"),
    path("dashboard/plazos/editar-plazo/<int:pk>/", views.EditarPlazoView.as_view(), name="editar_plazo"),
    path("dashboard/plazos/eliminar-plazo/<int:pk>", views.EliminarPlazo.as_view(), name="eliminar_plazo"),
    ##### plazo #####
    
    ##### obtener el interes ###
    path('obtener-interes/', views.obtener_interes, name='obtener_interes'),
    path('obtener-plazo/', views.obtener_plazo, name='obtener_plazo'),
    ##### obtener el interes ###
    
    path("editar-usuario/<int:pk>", views.EditarUsuarioUsers.as_view(), name="editar_usuario"),
    path("terminos/", views.TerminosCondiciones.as_view(), name="terminos_condiciones"),
]

yaab_corp/yaab_corp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static
# from yaab_corp.view import index_view
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("index/", include('applications.dashboard.urls')),
    path("", include('applications.landing.urls')),
    path("users/", include('applications.users.urls')),
    path("otro/", views.index_view, name="index"),
    path('account/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

yaab_corp/applications/dashboard/models.py
from django.db import models

# Create your models here.

class Productos(models.Model):
    nombre_credito = models.CharField(max_length=100,blank=True,null=True)
    
    def __str__(self):
        return str(self.nombre_credito) 

class Plazo(models.Model):    
    plazo_tiempo = models.CharField(max_length=100,blank=True,null=True) 
    interes_credito = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    

    class Meta:
        verbose_name = 'Plazo'
        verbose_name_plural = 'Plazos'
       

    def __str__(self):
        return str(self.plazo_tiempo) + ' ID:  ' + str(self.id) 



class Simulador(models.Model):
    tipo_credito = models.ForeignKey(Productos, on_delete=models.CASCADE,related_name='tipo_credito',null=True,blank=True)
    plazo_nombre = models.ForeignKey(Plazo,on_delete=models.CASCADE,related_name='nombre_plazo',null=True,blank=True)
    term = models.IntegerField(null=True,blank=True)
    amount = models.IntegerField(null=True,blank=True) 
    interest_rate = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    monthly_payment = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    
    class Meta:
        verbose_name = 'Simulador'
        verbose_name_plural = 'Simuladores'
    
    def __str__(self):
        return str(self.tipo_credito)

yaab_corp/applications/dashboard/forms.py
from django import forms 
from .models import Productos,Plazo,Simulador



class SimuladorForm(forms.ModelForm):
    
    tipo_credito = forms.ModelChoiceField(
        queryset= Productos.objects.all(),
        label = 'Tipo de crédito',        
        required=False,
        empty_label="Seleccionar",
        initial= 0,
        widget= forms.Select(
            attrs={
                'id':'id_tipo_credito',
                'class':'form-control btn btn-outline-light w-25 mt-2 rounded-pill',
                'placeholder':'Seleccionar',
                
            }
        )
    )
    
    amount = forms.DecimalField(
        label='Monto',
        required=False,
        widget=forms.widgets.NumberInput(
            attrs={
                'id': 'id_amount',
                'class': 'input-range d-none',                
                'type': 'range',
                'onchange':'rangeSlide(this.value)',
                'onmousemove':'rangeSlide(this.value)'
            }
        )
    )
    
    
    # def __init__(self, *args, **kwargs):
    #     super(SimuladorForm, self).__init__(*args, **kwargs)
    #     # Definir las opciones predeterminadas para el campo 'amount'
    #     self.fields['amount'].widget.choices = [('5000', '5000'), ('10000', '10000'), ('15000', '15000')]
    
    
    # def clean(self):
    #     cleaned_data = super().clean()
    #     tipo_credito = cleaned_data.get('tipo_credito')
        
    #     if tipo_credito:
    #         if tipo_credito.nombre_credito == 'Credito clasico':
    #             self.fields['amount'].widget.choices = [('5000','5000'),('10000','10000'),('15000','15000')]
    #         elif tipo_credito.nombre_credito == 'Empresarial':
    #             self.fields['amount'].widget.choices = [('20000','20000'),('25000','25000'),('30000','30000')]
    #     return cleaned_data
    
    
                
    
    # amount = forms.DecimalField(
        
    #     label = 'Monto',
    #     required=False,
       
    #     widget= forms.Select(
    #         attrs={
    #             'id': 'id_amount',
    #             'class':'form-control',
    #             'placeholder':'Seleccionar'
    #         }
    #     )
    # )
    

    interest_rate = forms.DecimalField(
            label='Interés',
            required=False,
            widget= forms.NumberInput(
                attrs={
                    'id': 'id_interest_rate',
                    'class':'form-control',
                    
                    
                }
            )
        )
        
    plazo_nombre = forms.ModelChoiceField(
        queryset= Plazo.objects.all(),
        label = 'Tipo de plazo',
        required=False,
        empty_label='Seleccionar',
        initial= 0,
        widget= forms.Select(
            attrs={
                'id':'id_plazo_nombre',
                'class':'form-control btn btn-outline-light w-25 mt-1 rounded-pill',
                'placeholder':'Tipo de plazo'
            }
        )
    )

    term = forms.IntegerField(
        
        label = 'Pagos',
        required=False,
        widget= forms.widgets.NumberInput(
            attrs={
                'id': 'id_term',
                'class':'input-range d-none',
                'type':'range',
                'placeholder':'12,14,16...',
                'onchange':'rangeSlideTerm(this.value)',
                'onmousemove':'rangeSlideTerm(this.value)'
            }
        )
    )
        
    class Meta:
        model = Simulador
        fields = ['tipo_credito','amount','interest_rate','plazo_nombre', 'term']


class ProductosForm(forms.ModelForm):
    nombre_credito =forms.CharField(
        max_length = 50,
        label = "Credito",
        required=False,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Credito...',
                    
                }
            )        
    )
    
    class Meta:
        model = Productos
        fields = ['nombre_credito']
        
        
        
class PlazoPagoForm(forms.ModelForm):
    
    plazo_tiempo = forms.CharField(
       max_length= 50,
        label='Plazo',
        required=False,
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder': 'semanal,quincenal o mensual...',
            }
        )
    )
    
    interes_credito =forms.DecimalField(        
        label = "Interes",
        required=False,
        widget=forms.NumberInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Interes...',
                    
                }
            )        
    )
    
    class Meta:
        model = Plazo 
        fields = ['plazo_tiempo','interes_credito']
        
        


    

yaab_corp/applications/dashboard/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView
from django.views.generic import ListView,UpdateView,CreateView,DeleteView
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render,redirect,get_object_or_404

from django.urls import reverse_lazy,reverse
from django.template.loader import get_template

from .models import Productos,Plazo,Simulador
from .forms import ProductosForm,PlazoPagoForm,SimuladorForm

from applications.users.models import User
from applications.users.forms import UserChangeForm

# Create your views here.from django.views.generic.base import TemplateView

class DashboardView(CreateView):
    template_name="index.html"
    form_class = SimuladorForm
    success_url = reverse_lazy('index')
    
    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        user = self.kwargs.get('pk')
        # context['usuario_id'] = User.objects.filter(id = user)
        context['pk'] = user
        context['simula'] = Simulador.objects.filter(id=user)
        # context['usuarios'] = User.objects.all()

        return context
    
    def form_valid(self, form):
        tipo_credito = form.cleaned_data['tipo_credito']
        plazo_nombre = form.cleaned_data['plazo_nombre']
        amount = form.cleaned_data['amount']
        interest_rate = form.cleaned_data['interest_rate']
        term = form.cleaned_data['term']

        # Realiza el cálculo
        monthly_interest_rate = (interest_rate / 12) / 100
        num_payments = term * 12
        monthly_payment = (amount * monthly_interest_rate) / (1 - (1 + monthly_interest_rate) ** -num_payments) + + + (amount / 12) 

        # Guarda los resultados en la base de datos o donde lo necesites
        # Aquí se asume que hay un modelo Loan para guardar los resultados
        loan = Simulador(amount=amount, tipo_credito = tipo_credito,plazo_nombre=plazo_nombre, interest_rate=interest_rate, term=term, monthly_payment=monthly_payment)
        loan.save()

        # return redirect('panel_app:panel_index')
        # return render(self.request,'panel/index.html', {'form': form, 'monthly_payment': monthly_payment})
        response_data = {'monthly_payment': monthly_payment}
        return JsonResponse(response_data)

def obtener_interes(request):
    if request.method == 'GET':
        product_id = request.GET.get('product_id')
        try:
            plazo = Plazo.objects.get(id=product_id)
            interest = plazo.interes_credito
            return JsonResponse({'interest': interest})
        except Productos.DoesNotExist:
            return JsonResponse({'interest': None})
        
def obtener_plazo(request):
    if request.method == 'GET':
        product_id = request.GET.get('product_id')
        try:
            product = Plazo.objects.get(id=product_id)
            plazo = product.semanas
            return JsonResponse({'plazo': plazo})
        except Productos.DoesNotExist:
            return JsonResponse({'plazo': None})
          


class PreguntasRespuestas(TemplateView):
    template_name = 'dashboard/preguntas-respuestas.html'
 
 
class ProductosView(ListView):
    model = Productos
    template_name = 'dashboard/productos/productos.html'
    context_object_name = 'productos'
    
    def get_queryset(self):
        producto = Productos.objects.all()
        return  producto
    
    def get_context_data(self, **kwargs):
        context = super(ProductosView,self).get_context_data(**kwargs)
        
        context["plazo"] = Plazo.objects.all()  
        
        return context
        

        
    
#####productos#####
    
class CreateProductosView(CreateView):
    model=Productos
    form_class = ProductosForm
    template_name = 'dashboard/productos/nuevo-producto.html'
    success_url = reverse_lazy('dashboard_app:productos_gral')

class EditarProducto(UpdateView):
    model = Productos
    template_name = 'dashboard/productos/editar-productos.html'
    form_class = ProductosForm
    success_url = reverse_lazy('dashboard_app:productos_gral')  
    
class EliminarProducto(DeleteView):
    model = Productos
    template_name = 'dashboard/productos/eliminar-productos.html'
    form_class = ProductosForm
    success_url = reverse_lazy('dashboard_app:productos_gral') 

#####productos#####

#####plazo#####

class CreatePlazoView(CreateView):
    model = Plazo
    form_class = PlazoPagoForm
    template_name = 'dashboard/plazos/nuevo-plazo.html'
    success_url = reverse_lazy('dashboard_app:productos_gral')
    
class EditarPlazoView(UpdateView):
    model = Plazo
    form_class = PlazoPagoForm
    template_name = 'dashboard/plazos/editar-plazo.html'
    success_url = reverse_lazy('dashboard_app:productos_gral') 

class EliminarPlazo(DeleteView):
    model = Plazo
    template_name = 'dashboard/plazos/eliminar-plazo.html'
    form_class = PlazoPagoForm
    success_url = reverse_lazy('dashboard_app:productos_gral') 
    
#####plazo#####


class EditarUsuarioUsers(UpdateView):
    model = User
    template_name = 'dashboard/registro-usuario/completar-registro.html'
    form_class = UserChangeForm
    success_url = reverse_lazy('index')
    
class TerminosCondiciones(TemplateView):
    template_name = 'dashboard/terminos-condiciones.html'

yaab_corp/templates/dashboard/productos/editar-productos.html
<!-- <h1>plazo</h1>

<!-- <form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Guardar</button>
</form> -->

{% load static %}

<div class="modal-dialog modal-lg" aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Modal actualizar</h4>
      <button type="button" class="close" data-bs-dismiss="modal">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <form
      method="POST"
      enctype="multipart/form-data"
      action="{% url 'dashboard_app:editar_productos' object.id %}"
    >
      {% csrf_token %}
      <div class="modal-body">
        <h1>Productos</h1>

        {{form.nombre_credito.label_tag}} {{form.nombre_credito}}

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-bsdismiss="modal">
            Cerrar
          </button>
          
          <button type="submit" class="btn btn-primary">Editar</button>
        </div>
      </div>
    </form>
  </div>
</div>

yaab_corp/templates/dashboard/productos/eliminar-productos.html
{% load static %}

<div class="modal-dialog modal-lg" aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Modal eliminar</h4>
      <button type="button" class="close" data-bs-dismiss="modal">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <h4 class="text-secondary">
      ¿Está seguro de que desea eliminar este producto?
    </h4>
    <form
      method="post"
      action="{% url 'dashboard_app:eliminar_productos' object.id %}"
    >
      {% csrf_token %}
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Cerrar
        </button>
        
        <button type="submit" class="btn btn-primary">Eliminar</button>
      </div>
    </form>
  </div>
</div>

yaab_corp/templates/dashboard/productos/nuevo-producto.html
{% load static %}

<div class="modal-dialog modal-lg" aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Modal title</h4>
       
      <button type="button" class="close" data-bs-dismiss="modal">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <form
      method="POST"
      action="{% url 'dashboard_app:nuevo_productos' %}"
      enctype="multipart/form-data"
    >
        {% csrf_token %}
        <div class="modal-body">
        <h1>Productos</h1>
        {{form.nombre_credito.label_tag}} {{form.nombre_credito}}
            
        <!-- <button type="submit" class="btn btn-primary">Save changes</button> -->

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
            Cerrar
            </button>
            
            <button type="submit" class="btn btn-primary">Crear</button>
        </div>
        </div>
    </form>
  </div>
</div>

yaab_corp/templates/dashboard/productos/productos.html
{% extends "dashboard/index.html" %}
<!---->
{% load static %}
<!---->
{% block title %}Datatables{% endblock title %}
<!---->
{% block extra_css %}

<!-- third party css -->
<link
  href="{% static 'libs/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'libs/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'libs/datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'libs/datatables.net-select-bs5/css//select.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<!-- third party css end -->

{% endblock extra_css %}
<!---->
{% block topbar %}
<!---->
<!---->
{% include "partials/topbar.html" with pagetitle="Productos | Plazos" %}
<!---->
{% endblock topbar %}
<!---->
{% block content %}



<!--productos-->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="mt-0 header-title">Crea y edita tus productos</h4>
                <p class="text-muted font-14 mb-3">
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aut corrupti incidunt expedita ea! Aut amet explicabo nisi suscipit repellendus, perferendis culpa 
                </p>
                <div class="d-flex justify-content-end mb-2">
                    <button type="button" class="btn btn-outline-secondary btn-sm border"          data-bs-toggle="modal" data-bs-target="#productosModal" 
                    onclick="abrirModalEdicion('{% url 'dashboard_app:nuevo_productos' %} ')" >
                    <!--url 'dashboard_app:nuevo_productos'      onclick="abrirModalEdicion('')"-->
                    Nuevo
                    </button>
                </div>
                <!--id="key-table"-->
                <table id="key-table" class="table dt-responsive nowrap table-hover">
                    <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    
                    <tr>
                      {% for item in productos %}
                      <td>{{item.nombre_credito}}</td>
                      <td>
                        <div class="dropdown">
                          <a
                            class="dropdown-toggle"
                            type="button"
                            id="dropdownMenuButton"
                            data-bs-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false"
                          >
                          <i class="mdi mdi-playlist-plus" style="color: black; font-size:18px;"></i>
                          </a>
                          <div
                            class="dropdown-menu"
                            aria-labelledby="dropdownMenuButton"
                          >
                            <button
                              type="button"
                              class="btn btn-outline-secondary btn-sm"
                              data-bs-toggle="modal"
                              data-bs-target="#actualizarProductosModal"
                              onclick="actualizarModalEdicion('{% url 'dashboard_app:editar_productos' pk=item.pk %}')"
                            >
                            
                              Editar
                            </button>

                            <button
                              type="button"
                              class="btn btn-outline-secondary btn-sm"
                              data-bs-toggle="modal"
                              data-bs-target="#eliminarProductosModal"
                              onclick="eliminarModalEdicion('{% url 'dashboard_app:eliminar_productos' pk=item.pk %}')"
                            >
                            
                              Eliminar
                            </button>
                          </div>
                        </div>
                      </td>
                      
                    </tr>
                    {% endfor %}
                    
                    </tbody>
                </table>
            </div>
        </div>
       
    </div>
</div> <!-- end row -->
<!--productos-->


<!--plazo-->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="mt-0 header-title">Crea y edita tus plazos</h4>
                <p class="text-muted font-14 mb-3">
                   Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aut corrupti incidunt expedita ea! Aut amet explicabo nisi suscipit repellendus, perferendis culpa
                </p>
                <div class="d-flex justify-content-end mb-2">
                    <button type="button" class="btn btn-outline-secondary btn-sm border"         data-bs-toggle="modal" data-bs-target="#plazoModal" 
                    onclick="plazoModal('{% url 'dashboard_app:nuevo_plazo' %}')">
                    <!--url 'dashboard_app:nuevo_plazo'-->
                    Nuevo
                    </button>
                </div>
                
                <table id="datatable" class="table dt-responsive nowrap table-hover">
                  <thead>
                    <tr>
                      <th>Tiempo</th>
                      <th>Semanas</th>
                      <!-- <th>Opción 2</th>
                      <th>Opción 3</th> -->
                      <th class="">Acciones</th>
                      <!-- <th>Username</th> -->
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in plazo %}
                    <tr>
                      <td>{{item.plazo_tiempo}}</td>
                      <td>{{item.interes_credito}}</td>
                    
                      <td class="">
                        <div class="dropdown">
                          <a
                            class="dropdown-toggle"
                            type="button"
                            id="dropdownMenuButton"
                            data-bs-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false"
                          >
                          <i class="mdi mdi-playlist-plus" style="color: black; font-size:18px;"></i>
                          </a>
                          <div
                            class="dropdown-menu"
                            aria-labelledby="dropdownMenuButton"
                          >
                            <button
                              type="button"
                              class="btn btn-outline-secondary btn-sm"
                              data-bs-toggle="modal"
                              data-bs-target="#actualizarPlazoModal"
                              onclick="actualizarModalPlazo('{% url 'dashboard_app:editar_plazo' pk=item.pk %}')"
                            >
                              Editar
                            </button>

                            <button
                              type="button"
                              class="btn btn-outline-secondary btn-sm"
                              data-bs-toggle="modal"
                              data-bs-target="#eliminarPlazoModal"
                              onclick="eliminarModalPlazo('{% url 'dashboard_app:eliminar_plazo' pk=item.pk %}')"
                            >
                              Eliminar
                            </button>
                          </div>
                        </div>
                      </td>
                      <!-- <td>@mdo</td> -->
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
       
    </div>
</div> <!-- end row -->
<!--plazo-->


<!--crear un nuevo producto-->
<div
  class="modal fade"
  id="productosModal"
  tabindex="-1"
  aria-labelledby="productosModalLabel"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg"></div>
</div>
<!--fin de crear un nuevo producto-->

<!--actualizar un nuevo producto-->
<div
  class="modal fade"
  id="actualizarProductosModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg"></div>
</div>
<!--fin de actualizar un nuevo producto-->

<!--eliminar un nuevo producto-->
<div
  class="modal fade"
  id="eliminarProductosModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg"></div>
</div>
<!--fin de eliminar un nuevo producto-->


<!--Modales Plazo-->
<div
  class="modal fade"
  id="plazoModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg"></div>
</div>

<div
  class="modal fade"
  id="actualizarPlazoModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg"></div>
</div>

<div
  class="modal fade"
  id="eliminarPlazoModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg"></div>
</div>

<!--fin Modales Plazo-->

{% include "partials/footer.html" %}
<!---->
{% endblock content %}
<!---->
{% block extra_js %}

<script>
  //crear producto
  function abrirModalEdicion(url) {
    $("#productosModal").load(url, function () {
      $(this).modal("show");
    });
  }
  //editar producto
  function actualizarModalEdicion(url) {
    $("#actualizarProductosModal").load(url, function () {
      $(this).modal("show");
    });
  }
  //eliminar producto
  function eliminarModalEdicion(url) {
    $("#eliminarProductosModal").load(url, function () {
      $(this).modal("show");
    });
  }

  //crear plazo
  function plazoModal(url) {
    $("#plazoModal").load(url, function () {
      $(this).modal("show");
    });
  }

  //editar plazo
  function actualizarModalPlazo(url) {
    $("#actualizarPlazoModal").load(url, function () {
      $(this).modal("show");
    });
  }

  //eliminar plazo
  function eliminarModalPlazo(url) {
    $("#eliminarPlazoModal").load(url, function () {
      $(this).modal("show");
    });
  }



</script>

<!-- third party js -->
<script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-bs5/js/dataTables.bootstrap5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-select/js/dataTables.select.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/build/vfs_fonts.js' %}"></script>
<!-- third party js ends -->

<!-- Datatables init -->
<script src="{% static 'js/pages/datatables.init.js' %}"></script>

<!---->


{% endblock extra_js %}