yaab_corp/applications/landing/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'landing_app'

urlpatterns = [
    path('',views.landing_view, name='landing')
]

yaab_corp/applications/users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'user_app'


urlpatterns = [
    path('registro/', views.RegistrarUsuario.as_view(), name='registro'),
    path('lista-usuarios/',views.ListaUsuarios.as_view(),name='lista_usuarios'),
    path('eliminar-usuarios/<int:pk>/',views.EliminarUsuarios.as_view(),name='eliminar_usuarios'),
    path('editar-usuarios/<int:pk>/',views.EditarUsuario.as_view(),name='editar_usuarios'),
]

yaab_corp/yaab_corp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static
# from yaab_corp.view import index_view
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("index/", include('applications.dashboard.urls')),
    path("", include('applications.landing.urls')),
    path("users/", include('applications.users.urls')),
    path("otro/", views.index_view, name="index"),
    path('account/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

yaab_corp/applications/users/forms.py
from django.forms import ModelForm
from django import forms
from .models import User
from django.utils.translation import gettext_lazy as _

class UserCreationForm(forms.ModelForm):
    # Define los campos que deseas incluir en el formulario
    # email = forms.EmailField()
    email =forms.EmailField(
        label = "Email",
        
        widget=forms.EmailInput(
                attrs={
                    # h-75 rounded-pill ml-1
                    'class':'form-control ',
                    'type': 'email',
                    'placeholder':'usuario@ejemplo.com',
                    
                }
            )        
    )
        
    password1 =forms.CharField(
        max_length=50,
        label = "Contraseña",
        widget=forms.PasswordInput(
                attrs={
                    'class':'form-control ',                    
                    'placeholder':'contraseña',
                    
                }
            )        
    )
    
      
    password2 =forms.CharField(
        max_length=50,
        label = "Contraseña",
        
        widget=forms.PasswordInput(
                attrs={
                    'class':'form-control ',                    
                    'placeholder':'confirmar contraseña...',
                    
                }
            )        
    )
    
    first_name =forms.CharField(
        max_length = 50,
        label = "Usuario",
        
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'nombres...',
                    
                }
            )        
    )
    
    last_name =forms.CharField(
        max_length = 50,
        label = "Usuario",
        
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'primer apellido...',
                    
                }
            )        
    )
   
    second_name =forms.CharField(
        max_length = 50,
        label = "Usuario",
        
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'segundo apellido...',
                    
                }
            )        
    )
    
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'first_name', 'last_name','second_name')
        

class UserChangeForm(forms.ModelForm):
    email =forms.CharField(
        max_length = 50,
        label = "Usuario",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Usuario...',
                    
                }
            )        
    )
    
    first_name =forms.CharField(
        max_length = 50,
        label = "Nombre",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Nombre...',
                    
                }
            )        
    )
    
    last_name =forms.CharField(
        max_length = 50,
        label = "Apellido",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Apellido...',
                    
                }
            )        
    )
    
    second_name =forms.CharField(
        max_length = 50,
        label = "Apellido",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Apellido...',
                    
                }
            )        
    )
  
    
    telefono_particular =forms.CharField(
        max_length = 50,
        label = "Teléfono particular",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Teléfono...',
                    
                }
            )        
    )
        
    fecha_nac =forms.DateField(
        required=True,
        widget=forms.DateInput(
                attrs={
                    'class':'form-control ',
                    'type': 'date'
                    
                    
                }
            )        
    )
    
    curp =forms.FileField(
        label = "CURP",
        required=True,
        widget=forms.ClearableFileInput(
                attrs={
                    'accept':'application/pdf',
                    'class':'form-control ',
                    'placeholder':'CURP...',
                    'type': 'file',
                    
                }
            ),        
        help_text=_('Solo se permiten archivos PDF')
    )
    
    documento_ine =forms.FileField(
        label = "INE",
        required=True,
        widget=forms.ClearableFileInput(
                attrs={
                    'accept':'application/pdf',
                    'class':'form-control ',
                    'placeholder':'INE...',
                    'type': 'file',
                    
                }
            ),        
        help_text=_('Solo se permiten archivos PDF')
    )
    
    
    
    comprobante_domicilio =forms.FileField(
        label = "Comprobante domicilio:",
        required=True,
        widget=forms.ClearableFileInput(
                attrs={
                    'accept':'application/pdf',
                    'class':'form-control ',
                    'placeholder':'Comprobante domicilio:...',
                    'type': 'file',
                    
                    
                }
            ),        
        help_text=_('Solo se permiten archivos PDF')
    )
    
    documento_ine_aval =forms.FileField(
        label = "INE:",
        required=True,
        widget=forms.ClearableFileInput(
                attrs={
                    'accept':'application/pdf',
                    'class':'form-control ',
                    'placeholder':'INE:...',
                    'type':'file',
                    
                }
            ),        
        help_text=_('Solo se permiten archivos PDF')
    )
    
    
    comprobante_domicilio_aval =forms.FileField(
        label = "Comprobante domicilio:",
        required=True,
        widget=forms.ClearableFileInput(
                attrs={
                    'accept':'application/pdf',
                    'class':'form-control ',
                    'placeholder':'Comprobante domicilio:...',
                    'type':'file',
                    
                }
            ),        
        help_text=_('Solo se permiten archivos PDF')
    )
    
    curp_aval =forms.FileField(
        label = "CURP:",
        required=True,
        widget=forms.ClearableFileInput(
                attrs={
                    'accept':'application/pdf',
                    'class':'form-control ',
                    'placeholder':'CURP:...',
                    'type':'file',
                    
                }
            ),        
        help_text=_('Solo se permiten archivos PDF')
    )
    
    rfc =forms.CharField(
        max_length = 50,
        label = "RFC",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'RFC...',
                    
                }
            )        
    )
    
    estado_civil =forms.CharField(
        max_length = 50,
        label = "Estado Civil",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Estado Civil...',
                    
                }
            )        
    )
    
    genero =forms.CharField(
        max_length = 50,
        label = "Genero",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Genero...',
                    
                }
            )        
    )
    
    nacionalidad =forms.CharField(
        max_length = 50,
        label = "Nacionalidad",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Nacionalidad...',
                    
                }
            )        
    )
    
    pais =forms.CharField(
        max_length = 50,
        label = "Pais",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Estado...',
                    
                }
            )        
    )
    
    estado =forms.CharField(
        max_length = 50,
        label = "Estado",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Estado...',
                    
                }
            )        
    )
    
    celular =forms.CharField(
        max_length = 50,
        label = "Celular",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Celular...',
                    
                }
            )        
    )
    
    numero_dependientes =forms.CharField(
        max_length = 50,
        label = "Dependientes",
        required=True,
        widget=forms.TextInput(
                attrs={
                    'class':'form-control ',
                    'placeholder':'Dependientes...',
                    
                }
            )        
    )
    
    
    calle_numero =forms.CharField(
        max_length = 50,
        label = "Calle y Numero",

yaab_corp/applications/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.views.generic import View,TemplateView,ListView,UpdateView,CreateView,DeleteView
from .models import User
from .forms import UserCreationForm,UserChangeForm
# Create your views here.

class RegistrarUsuario(CreateView):
    model = User
    template_name = 'users/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    
    def form_valid(self, form):
        # Obtenemos los datos del formulario
        email = form.cleaned_data['email']
        password = form.cleaned_data['password1']  # Obtenemos la contraseña

        # Creamos una instancia del modelo de usuario pero no la guardamos aún
        user = form.save(commit=False)
        # Usamos make_password para cifrar la contraseña antes de guardarla
        user.password = make_password(password)
        user.save()
        return super().form_valid(form)
    
    
class EditarUsuario(UpdateView):
    model = User
    template_name = 'users/editar-usuario.html'
    form_class = UserChangeForm
    success_url = reverse_lazy('user_app:lista_usuarios')

class EliminarUsuarios(DeleteView):
    model = User
    template_name = 'users/eliminar-usuario.html'
    # form_class = CreateUserForm
    success_url = reverse_lazy('user_app:lista_usuarios')
    
class ListaUsuarios(ListView):
    # model = User
    template_name = 'users/listar-usuarios.html'
    context_object_name = 'lista'

    def get_queryset(self):
        listar = User.objects.all()
        return listar

yaab_corp/templates/users/eliminar-usuario.html
{% load static %}

<div class="modal-dialog modal-lg" aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title" id="myModalLabel">Modal eliminar</h4>
      <button type="button" class="close" data-bs-dismiss="modal">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <h4 class="text-secondary">
      ¿Está seguro de que desea eliminar este usuario?
    </h4>
    <form
      method="post"
      action="{% url 'user_app:eliminar_usuarios' object.id %}"
    >
      {% csrf_token %}
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Cerrar
        </button>
       
        <button type="submit" class="btn btn-primary">Eliminar</button>
      </div>
    </form>
  </div>
</div>

yaab_corp/templates/users/listar-usuarios.html
{% extends "dashboard/index.html" %}
<!---->
{% load static %}
<!---->
{% block title %}Datatables{% endblock title %}
<!---->
{% block extra_css %}

<!-- third party css -->
<link
  href="{% static 'libs/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'libs/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'libs/datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<link
  href="{% static 'libs/datatables.net-select-bs5/css//select.bootstrap5.min.css' %}"
  rel="stylesheet"
  type="text/css"
/>
<!-- third party css end -->

{% endblock extra_css %}
<!---->
{% block topbar %}
<!---->
<!---->
{% include "partials/topbar.html" with pagetitle="Usuarios" %}
<!---->
{% endblock topbar %}
<!---->
{% block content %}



<!--productos-->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="mt-0 header-title">Edita los usuarios</h4>
                <p class="text-muted font-14 mb-3">
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aut corrupti incidunt expedita ea! Aut amet explicabo nisi suscipit repellendus, perferendis culpa 
                </p>
                
                <!--id="key-table"    table dt-responsive nowrap table-hover-->
                <table id="datatable" class=" table dt-responsive nowrap table-hover">
                    <thead>
                    <tr>
                        <th>Usuario</th>
                        <th>Nombre</th>
                        <th>Apellido Paterno</th>
                        <th>Apellido Materno</th>
                        <th>Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in lista %}
                    <tr>
                        <td>{{item.email}}</td>
                        <td>{{item.first_name | upper}}</td>
                        <td>{{item.last_name | upper}}</td>
                        <td>{{item.second_name | upper}}</td>

                        <td>
                        <div class="dropdown">
                            <a
                            class="dropdown-toggle"
                            type="button"
                            id="dropdownMenuButton"
                            data-bs-toggle="dropdown"
                            aria-haspopup="true"
                            aria-expanded="false"
                            >
                            <i class="mdi mdi-playlist-plus" style="color: black; font-size:18px;"></i>
                            </a>
                            <div
                            class="dropdown-menu"
                            aria-labelledby="dropdownMenuButton"
                            >
                            <button
                                type="button"
                                class="btn btn-outline-secondary btn-sm"
                                data-bs-toggle="modal"
                                data-bs-target="#actualizarUsuariosModal"
                                onclick="actualizarModalUser('{% url 'user_app:editar_usuarios' pk=item.id %}')"
                            >
                                Editar
                            </button>

                            <button
                                type="button"
                                class="btn btn-outline-secondary btn-sm"
                                data-bs-toggle="modal"
                                data-bs-target="#eliminarUsuarioModal"
                                onclick="eliminarModalUser('{% url 'user_app:eliminar_usuarios' pk=item.pk %}')"
                            >
                                Eliminar
                            </button>
                            </div>
                        </div>
                        </td>
                    </tr>

                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
       
    </div>
</div> <!-- end row -->
<!--productos-->


<!--modal eliminar usuarios-->
<div
  class="modal fade"
  id="eliminarUsuarioModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg"></div>
</div>
<!--modal eliminar usuarios-->

<!--modal editar usuarios-->
<div
  class="modal fade"
  id="actualizarUsuariosModal"
  tabindex="-1"
  role="dialog"
  aria-hidden="true"
>
  <div class="modal-dialog modal-lg"></div>
</div>
<!--modal editar usuarios-->



{% include "partials/footer.html" %}
<!---->
{% endblock content %}
<!---->
{% block extra_js %}

<script>
  //eliminar usuario
  function eliminarModalUser(url) {
    $("#eliminarUsuarioModal").load(url, function () {
      $(this).modal("show");
    });
  }
  //editar usuario
  function actualizarModalUser(url) {
    $("#actualizarUsuariosModal").load(url, function () {
      $(this).modal("show");
    });
  }
  

</script>

<!-- third party js -->
<script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-bs5/js/dataTables.bootstrap5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-select/js/dataTables.select.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'libs/pdfmake/build/vfs_fonts.js' %}"></script>
<!-- third party js ends -->

<!-- Datatables init -->
<script src="{% static 'js/pages/datatables.init.js' %}"></script>

<!---->


{% endblock extra_js %}

yaab_corp/templates/users/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

{% include "partials/title-meta.html" with title="Registro | Yaab" %}

<style>
  

    .btn-wsp{
        position:fixed;
        width:60px;
        height:60px;
        line-height: 63px;
        bottom:25px;
        right:25px;
        background:#3b3d3c;
        color:#FFF;
        border-radius:50px;
        text-align:center;
        font-size:35px;
        box-shadow: 0px 1px 10px rgba(0,0,0,0.3);
        z-index:100;
        transition: all 300ms ease;
    }
    .btn-wsp:hover{
        background: #d5dbd7;
    }
    @media only screen and (min-width:320px) and (max-width:768px){
        .btn-wsp{
            width:63px;
            height:63px;
            line-height: 66px;
      }
    }
</style>

{% include "partials/head-css.html" %}



<body class="loading " style="background: url('../../static/images/landing/yaab_corp_reg.png'); background-size:cover;"  >

    <div class="account-pages mt-2 mb-2 bg-register"  >
        <div class="container ">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-8 col-xl-8">
                    <div class="text-center">
                        <a href="{% url 'index' %}">
                            <img src="{% static 'images/landing/financiera_logo.png' %}" alt="" width="30%" class="mx-auto">
                        </a>
                        
                    </div>
                    <div class="card">  

                        <div class="card-body p-4">
                            
                            <div class="text-center mb-4">
                                <h4 class="text-uppercase mt-0">Registrate</h4>
                            </div>

                            <form method="POST" action="" enctype="multipart/form-data">
                                {% csrf_token %}

                                <div class="row mb-3">
                                    <div class="col">
                                        <label for="fullname" class="form-label">Usuario</label>
                                        {{form.email}}
                                    </div>
                                    <div class="col">
                                        <label for="emailaddress" class="form-label">Nombres</label>
                                        {{form.first_name}}
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <div class="col">
                                        <label for="password" class="form-label">Primer Apellido</label>
                                        {{form.last_name}}
                                    </div>
                                    <div class="col">
                                        <label for="password" class="form-label">Segundo Apellido</label>
                                        {{form.second_name}}
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <div class="col">
                                        <label for="password" class="form-label">contraseña</label>
                                        {{form.password1}}
                                    </div>
                                    <div class="col">
                                        <label for="password" class="form-label">confirmar contraseña</label>
                                        {{form.password2}}                                        
                                    </div>
                                </div>

                                <div class="mb-3 d-none">
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input" id="checkbox-signup">
                                        <label class="form-check-label" for="checkbox-signup">acepto <a href="javascript: void(0);" class="text-dark">Terminos y condiciones</a></label>
                                    </div>
                                </div>

                                <div class="mb-3 text-center d-grid">
                                    <button class="btn btn-secondary w-50 mx-auto" type="submit"> Registrar </button>
                                </div>

                            </form>

                        </div> <!-- end card-body -->
                    </div>
                    <!-- end card -->

                    <div class="row mt-3">
                        <div class="col-12 text-center">
                            <p class="text-muted">Ya tienes cuenta?  <a href="{% url 'login' %}" class="text-white ms-1"><b>Inicia Sesion aqui</b></a></p>
                        </div> <!-- end col -->
                    </div>
                    <!-- end row -->

                </div> <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- end page -->

        <a href="{% url 'landing_app:landing' %}" class="btn-wsp mb-4" target="_blank">
	    <i class="mdi mdi-home"></i>
	  </a>

    <!-- Vendor -->
    {% include "partials/vendor.html" %}

    <!-- App js -->
    <script src="{% static 'js/app.min.js' %}"></script>
    
</body>