yaab_corp/applications/dashboard/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'dashboard_app'

urlpatterns = [
    path("",views.DashboardView.as_view(), name="index"),
    path('preguntas-respuestas/',views.PreguntasRespuestas.as_view(),name='preguntas_respuestas'),
    path('productos/productos-gral/',views.ProductosView.as_view(),name='productos_gral'),
    ##### producto #####
    path("dashboard/productos/nuevo-producto/",views.CreateProductosView.as_view(),name="nuevo_productos"),
    path('dashboard/productos/editar-productos/<int:pk>/',views.EditarProducto.as_view(),name='editar_productos'),
    path('dashboard/productos/eliminar-productos/<int:pk>/',views.EliminarProducto.as_view(),name='eliminar_productos'),
    
    ##### producto #####
    ##### plazo #####
    path("dashboard/plazos/nuevo-plazo/", views.CreatePlazoView.as_view(), name="nuevo_plazo"),
    path("dashboard/plazos/editar-plazo/<int:pk>/", views.EditarPlazoView.as_view(), name="editar_plazo"),
    path("dashboard/plazos/eliminar-plazo/<int:pk>", views.EliminarPlazo.as_view(), name="eliminar_plazo"),
    ##### plazo #####
    
    ##### obtener el interes ###
    path('obtener-interes/', views.obtener_interes, name='obtener_interes'),
    path('obtener-plazo/', views.obtener_plazo, name='obtener_plazo'),
    ##### obtener el interes ###
    
    path("editar-usuario/<int:pk>", views.EditarUsuarioUsers.as_view(), name="editar_usuario"),
    path("terminos/", views.TerminosCondiciones.as_view(), name="terminos_condiciones"),
]

yaab_corp/applications/landing/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'landing_app'

urlpatterns = [
    path('',views.landing_view, name='landing')
]

yaab_corp/applications/users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'user_app'


urlpatterns = [
    path('registro/', views.RegistrarUsuario.as_view(), name='registro'),
    path('lista-usuarios/',views.ListaUsuarios.as_view(),name='lista_usuarios'),
    path('eliminar-usuarios/<int:pk>/',views.EliminarUsuarios.as_view(),name='eliminar_usuarios'),
    path('editar-usuarios/<int:pk>/',views.EditarUsuario.as_view(),name='editar_usuarios'),
]

yaab_corp/yaab_corp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.conf.urls.static import static
# from yaab_corp.view import index_view
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("index/", include('applications.dashboard.urls')),
    path("", include('applications.landing.urls')),
    path("users/", include('applications.users.urls')),
    path("otro/", views.index_view, name="index"),
    path('account/login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

yaab_corp/templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>
      {% block title %}{% endblock title %} | Adminto - Responsive Admin
      Dashboard Template
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      content="A fully featured admin theme which can be used to build CRM, CMS, etc."
      name="description"
    />
    <meta content="coderthemes" name="author" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />

    <!-- App css -->

    <link
      href="{% static 'css/app.css' %}"
      rel="stylesheet"
      type="text/css"
      id="app-style"
    />

    <!-- icons -->
    <link
      href="{% static 'css/icons.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    {% block css %} {% block extra_css %} {% endblock extra_css %}
    <!---->
    {% include "partials/head-css.html" %} {% endblock css %}
  </head>

  <body
    class="loading"
    data-layout-color="light"
    data-layout-mode="default"
    data-layout-size="fluid"
    data-topbar-color="light"
    data-leftbar-position="fixed"
    data-leftbar-color="light"
    data-leftbar-size="default"
    data-sidebar-user="true"
  >
    <div id="wrapper">
      {% block topbar %} {% endblock topbar %}
      <!---->

      {%include "partials/left-sidebar.html" %}

      <div class="content-page">
        <div class="content">
          <div class="container-fluid">
            {% block content %} {% endblock content %}
          </div>
        </div>
      </div>
    </div>

    {% include "partials/right-sidebar.html" %} {% include
    "partials/vendor.html" %} {% block extra_js %} {% endblock extra_js %}

    <!-- App js-->
    <script src="{% static 'js/app.min.js' %}"></script>
  </body>
</html>

yaab_corp/templates/partials/footer.html
<!-- Footer Start -->
<footer class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <script>
          document.write(new Date().getFullYear());
        </script>
        &copy; Inversiones y Servicios Financieros<a href="">YAAB</a>
      </div>
      <div class="col-md-6">
        <div class="text-md-end footer-links d-none d-sm-block">
          <a href="{% url 'landing_app:landing' %}">Inicio</a>
          <!-- <a href="javascript:void(0);">Help</a>
          <a href="javascript:void(0);">Contact Us</a> -->
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- end Footer -->

yaab_corp/templates/partials/head-css.html
{% load static %}
<!-- App css -->
<link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css" id="app-style" />

<!-- icons -->
<link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />

yaab_corp/templates/partials/layout-horizontal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock title %} | Adminto - Responsive Admin Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description"/>
    <meta content="Coderthemes" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    {% block css %}
        {% block extra_css %} {% endblock extra_css %}
        {% include "partials/head-css.html" %}
    {% endblock css %}
</head>

<body class="loading" data-layout-mode="horizontal" data-layout-color="light" data-layout-size="fluid"
      data-topbar-color="dark" data-leftbar-position="fixed">


<div id="wrapper">

    {% block topbar %}
    {% endblock topbar %}

    {% include "partials/topbar-dark.html" %}
    {% include "partials/horizontal-nav.html" %}

    <div class="content-page">
        <div class="content">

            <div class="container-fluid">
                {% block content %}
                {% endblock content %}
            </div>

        </div>

        {% include "partials/footer.html" %}

    </div>

</div>

{% include "partials/right-sidebar.html" %}

{% include "partials/vendor.html" %}

{% block extra_js %} {% endblock extra_js %}

<!-- App js-->
<script src="{% static 'js/app.min.js' %}"></script>

</body>
</html>

yaab_corp/templates/partials/layout-preloader.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock title %} | Adminto - Responsive Admin Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description"/>
    <meta content="Coderthemes" name="author"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    {% block css %}
        {% block extra_css %} {% endblock extra_css %}
        {% include "partials/head-css.html" %}
    {% endblock css %}
</head>

<body class="loading" data-layout-color="light" data-layout-mode="default" data-layout-size="fluid"
      data-topbar-color="light" data-leftbar-position="fixed" data-leftbar-color="light" data-leftbar-size='default'
      data-sidebar-user='true'>

        <!-- Pre-loader -->
        <div id="preloader">
            <div id="status">
                <div class="spinner">Loading...</div>
            </div>
        </div>
        <!-- End Preloader-->

<div id="wrapper">

    {% block topbar %}
    {% endblock topbar %}

    {% include "partials/left-sidebar.html" %}

    <div class="content-page">
        <div class="content">

            <div class="container-fluid">
                {% block content %}
                {% endblock content %}
            </div>

        </div>

        {% include "partials/footer.html" %}

    </div>

</div>

{% include "partials/right-sidebar.html" %}

{% include "partials/vendor.html" %}

{% block extra_js %} {% endblock extra_js %}

<!-- App js-->
<script src="{% static 'js/app.min.js' %}"></script>

</body>
</html>

yaab_corp/templates/partials/layout-vertical.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock title %} | Yaab Fianciera</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      content="A fully featured admin theme which can be used to build CRM, CMS, etc."
      name="description"
    />
    <meta content="Coderthemes" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'images/landing/yaab_corp.png' %}" />

    {% block css %} {% block extra_css %} {% endblock extra_css %}
    <!---->
    {% include "partials/head-css.html" %} {% endblock css %}
  </head>

  <body
    class="loading"
    data-layout-color="light"
    data-layout-mode="default"
    data-layout-size="fluid"
    data-topbar-color="light"
    data-leftbar-position="fixed"
    data-leftbar-color="dark"
    data-leftbar-size="default"
    data-sidebar-user="true"
  >
    <div id="wrapper">
      {% block topbar %} {% endblock topbar %}
      <!---->
      {% include "partials/left-sidebar.html" %}

      <div class="content-page">
        <div class="content">
          <div class="container-fluid">
            {% block content %} {% endblock content %}
          </div>
        </div>

        {% include "partials/footer.html" %}
      </div>
    </div>

    {% include "partials/right-sidebar.html" %}
    <!---->
    {% include "partials/vendor.html" %} {% block extra_js %}
    <!---->
    {% endblock extra_js %}

    <!-- App js-->
    <script src="{% static 'js/app.min.js' %}"></script>
  </body>
</html>

yaab_corp/templates/partials/left-sidebar.html
{% load static %}

<style>
  .texto-blanco {
    color: #c5c9cd;
  }

  .texto-blanco:hover {
    color: #ffffff;
  }
</style>
<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">
  <div class="h-100" data-simplebar>
    <!-- User box -->
    <div class="user-box text-center mb-3">
      <img
        src="{% static 'images/landing/yaab_corp.png' %}"
        alt="user-img"
        title="Mat Helme"
        class="rounded-circle img-thumbnail avatar-md"
      />
      <div class="dropdown ">
        <a
          href="#"
          class="user-name dropdown-toggle h5 mt-2 mb-1 d-block"
          data-bs-toggle="dropdown"
          aria-expanded="false"
          >{{user.first_name}} {{user.last_name}}</a
        >
        <div class="dropdown-menu user-pro-dropdown">
          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item notify-item">
            <i class="fe-user me-1"></i>
            <span>My Account</span>
          </a>

          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item notify-item">
            <i class="fe-settings me-1"></i>
            <span>Settings</span>
          </a>

          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item notify-item">
            <i class="fe-lock me-1"></i>
            <span>Lock Screen</span>
          </a>

          <!-- item-->
          <a href="javascript:void(0);" class="dropdown-item notify-item">
            <i class="fe-log-out me-1"></i>
            <span>Logout</span>
          </a>
        </div>
      </div>

      <p class="text-muted left-user-info">{{user.rfc}}</p>

      <ul class="list-inline d-none">
        <li class="list-inline-item">
          <a href="#" class="text-muted left-user-info">
            <i class="mdi mdi-cog"></i>
          </a>
        </li>

        <li class="list-inline-item">
          <a href="#">
            <i class="mdi mdi-power"></i>
          </a>
        </li>
      </ul>
    </div>

    <!--- Sidemenu -->
    <div id="sidebar-menu">
      <ul id="side-menu">
        <li class="menu-title">Panel de administración</li>

        <li>
          <a href="{% url 'dashboard_app:index' %}">
            <!-- <iconify-icon icon="mdi:view-dashboard"></iconify-icon> -->
            <i class="mdi mdi-view-dashboard" style="color: #ffff"></i>
            <!-- <span class="badge rounded-pill float-end">9+</span> -->
            <span class="texto-blanco"> Inicio </span>
          </a>
        </li>

        <li class="menu-title mt-2">Administrativo</li>

        <li>
          <a href="#sideBarAdministrativo" data-bs-toggle="collapse">
            <i class="mdi mdi-folder-account" style="color: #ffff"></i>
            <span class="texto-blanco"> Áreas </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sideBarAdministrativo">
            <ul class="nav-second-level">
              <li>
                <!--url 'inbox'-->
                <a href="{% url 'dashboard_app:productos_gral' %}">
                  <span class="texto-blanco">Alta de productos</span>
                </a>
              </li>
              <li>
                <!--url 'templates'-->
                <a href="{% url 'user_app:lista_usuarios' %}"> <span class="texto-blanco">Usuarios</span></a>
              </li>
            </ul>
          </div>
        </li>

        <li class="menu-title mt-2">General usuarios</li>

        <li>
          <a href="#sidebarUsuarios" data-bs-toggle="collapse">
            <i class="mdi mdi-account-star" style="color: #ffff"></i>
            <span class="texto-blanco"> Opciones </span>
            <span class="menu-arrow" style="color: #ffff"></span>
          </a>
          <div class="collapse" id="sidebarUsuarios">
            <ul class="nav-second-level">
              <li>
                <!--url 'inbox'-->
                <a href="{%url 'dashboard_app:preguntas_respuestas'%}">
                  <span class="texto-blanco">Preguntas y repuestas</span>
                </a>
              </li>
              
            </ul>
          </div>
        </li>
      </ul>
    </div>
    <!-- End Sidebar -->

    <div class="clearfix"></div>
  </div>
  <!-- Sidebar -left -->
</div>
<!-- Left Sidebar End -->

yaab_corp/templates/partials/right-sidebar.html
<style>
  .rightbar-title {
    background-color: #343a40 !important;
    padding: 25.5px 25px;
    color: #fff;
  }
</style>

<!-- Right Sidebar -->
<div class="right-bar">
  <div data-simplebar class="h-100">
    <div class="rightbar-title">
      <a href="javascript:void();" class="right-bar-toggle float-end d-none">
        <i class="mdi mdi-close"></i>
      </a>
      <h4 class="font-16 m-0 text-white">Configura tu vista</h4>
    </div>

    <!-- Tab panes -->
    <div class="tab-content pt-0">
      <div class="tab-pane active" id="settings-tab" role="tabpanel">
        <div class="p-3">
          <div class="alert alert-secondary" role="alert">
            <strong>Personaliza </strong> la combinación de colores en genral,
            el diseño, etc..
          </div>

          <h6 class="fw-medium font-14 mt-4 mb-2 pb-1">Color Scheme</h6>
          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="layout-color"
              value="light"
              id="light-mode-check"
              checked
            />
            <label class="form-check-label" for="light-mode-check"
              >Light Mode</label
            >
          </div>

          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="layout-color"
              value="dark"
              id="dark-mode-check"
            />
            <label class="form-check-label" for="dark-mode-check"
              >Dark Mode</label
            >
          </div>

          <!-- Width -->
          <h6 class="fw-medium font-14 mt-4 mb-2 pb-1 d-none">Width</h6>
          <div class="form-check form-switch mb-1 d-none">
            <input
              type="checkbox"
              class="form-check-input"
              name="layout-size"
              value="fluid"
              id="fluid"
              checked
            />
            <label class="form-check-label" for="fluid-check">Fluid</label>
          </div>
          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="layout-size"
              value="boxed"
              id="boxed"
            />
            <label class="form-check-label" for="boxed-check">Boxed</label>
          </div>

          <!-- Menu positions -->
          <h6 class="fw-medium font-14 mt-4 mb-2 pb-1 d-none">
            Menus (Leftsidebar and Topbar) Positon
          </h6>

          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="leftbar-position"
              value="fixed"
              id="fixed-check"
              checked
            />
            <label class="form-check-label" for="fixed-check">Fixed</label>
          </div>

          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="leftbar-position"
              value="scrollable"
              id="scrollable-check"
            />
            <label class="form-check-label" for="scrollable-check"
              >Scrollable</label
            >
          </div>

          <!-- Left Sidebar-->
          <h6 class="fw-medium font-14 mt-4 mb-2 pb-1">Left Sidebar Color</h6>

          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="leftbar-color"
              value="dark"
              id="dark"
              checked
            />
            <label class="form-check-label" for="dark-check">Dark</label>
          </div>

          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="leftbar-color"
              value="light"
              id="light"
            />
            <label class="form-check-label" for="light-check">Light</label>
          </div>

          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="leftbar-color"
              value="brand"
              id="brand"
            />
            <label class="form-check-label" for="brand-check">Brand</label>
          </div>

          <div class="form-check form-switch mb-3">
            <input
              type="checkbox"
              class="form-check-input"
              name="leftbar-color"
              value="gradient"
              id="gradient"
            />
            <label class="form-check-label" for="gradient-check"
              >Gradient</label
            >
          </div>

          <!-- size -->
          <h6 class="fw-medium font-14 mt-4 mb-2 pb-1">Left Sidebar Size</h6>

          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="leftbar-size"
              value="default"
              id="default-size-check"
              checked
            />
            <label class="form-check-label" for="default-size-check"
              >Default</label
            >
          </div>

          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="leftbar-size"
              value="condensed"
              id="condensed-check"
            />
            <label class="form-check-label" for="condensed-check"
              >Condensed <small>(Extra Small size)</small></label
            >
          </div>

          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="leftbar-size"
              value="compact"
              id="compact-check"
            />
            <label class="form-check-label" for="compact-check"
              >Compact <small>(Small size)</small></label
            >
          </div>

          <!-- User info -->
          <h6 class="fw-medium font-14 mt-4 mb-2 pb-1">Sidebar User Info</h6>

          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="sidebar-user"
              value="true"
              id="sidebaruser-check"
            />
            <label class="form-check-label" for="sidebaruser-check"
              >Enable</label
            >
          </div>

          <!-- Topbar -->
          <h6 class="fw-medium font-14 mt-4 mb-2 pb-1">Topbar</h6>

          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="topbar-color"
              value="dark"
              id="darktopbar-check"
              checked
            />
            <label class="form-check-label" for="darktopbar-check">Dark</label>
          </div>

          <div class="form-check form-switch mb-1">
            <input
              type="checkbox"
              class="form-check-input"
              name="topbar-color"
              value="light"
              id="lighttopbar-check"
            />
            <label class="form-check-label" for="lighttopbar-check"
              >Light</label
            >
          </div>

          <div class="d-grid mt-4 d-none">
            <button class="btn btn-primary" id="resetBtn">
              Reset to Default
            </button>
            <a
              href="https://1.envato.market/admintoadmin"
              class="btn btn-danger mt-3"
              target="_blank"
              ><i class="mdi mdi-basket me-1"></i> Purchase Now</a
            >
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

<!-- Right bar overlay-->
<div class="rightbar-overlay"></div>

yaab_corp/templates/partials/title-meta.html
{% load static %}
<meta charset="utf-8" />
<title>{{title}} </title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
<meta content="Coderthemes" name="author" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<!-- App favicon -->
<link rel="shortcut icon" href="{% static 'images/landing/yaab_corp.png' %}">

yaab_corp/templates/partials/vendor.html
{% load static %}
<!-- Vendor -->
<script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
<script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'libs/simplebar/simplebar.min.js' %}"></script>
<script src="{% static 'libs/node-waves/waves.min.js' %}"></script>
<script src="{% static 'libs/waypoints/lib/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'libs/jquery.counterup/jquery.counterup.min.js' %}"></script>
<script src="{% static 'libs/feather-icons/feather.min.js' %}"></script>